name: ForTune-CA

on:
  push:
    branches: 
       - 'v[0-9]+.[0-9]+' #setup1 validate branch name format according to assignment
      

jobs:
  fortune-CA:
    runs-on: ubuntu-latest


    steps:
     #just testing checkout actions
    - name: List file
      run: |
        pwd
        ls -al
        echo "hello" 
        echo "world"
       
    - name: using Checkout
      uses: actions/checkout@v3
    - name: List file
      run: |
        pwd
        ls -al
        echo "hello"
       
    #setup3 Create a release using the branch name
    #using create-release actions
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}