name: ForTune-CA

on:
  push:
    branches: 
       - 'v[0-9]+.[0-9]+' #setup1 validate branch name format according to assignment
      

jobs:
  fortune-CA:
    runs-on: ubuntu-latest


    steps:
     #just testing checkout actions
    - name: List file
      run: |
        pwd
        ls -al
        echo "hello" 
        echo "world"
       
    - name: using Checkout
      uses: actions/checkout@v3
    - name: List file
      run: |
        pwd
        ls -al
        echo "hello"
        echo "world"
       
    #setup3 Create a release using the branch name
    #using create-release action
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}

    
    #setup4 Send a notification to Slack
    #using Slack notification action
    - name: Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.KEY_RW }}
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nSoe La Pyae Htun"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Metriculation:*\nA0265079U"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\ne123456@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\nhttps://github.com/soelapyae-htun/fortune-CA"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\nhttps://military-quiver-production.up.railway.app/"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://military-quiver-production.up.railway.app/|Open Application>"
                }
              }
            ]
          }
   

      env:
        SLACK_WEBHOOK_URL: ${{ secrets.KEY_CL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK